name: Build APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-pip build-essential git python3-dev zlib1g-dev openjdk-17-jdk unzip wget

      - name: Install Aidl
        run: |
          wget https://dl.google.com/android/repository/platform-tools-latest-linux.zip
          unzip platform-tools-latest-linux.zip
          sudo cp platform-tools/aidl /usr/bin/aidl
          sudo chmod +x /usr/bin/aidl
          aidl --version

      - name: Install Buildozer
        run: |
          pip install --upgrade pip
          pip install buildozer cython

      - name: Build APK
        run: |
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: auditor-app
          path: bin/*.apk
